#!/bin/sh

phd=/run/user/$UID/protonhax

usage() {
    echo "Usage:"
    echo "protonhax init <cmd>"
    printf "\tShould only be called by Steam with \"protonhax init %%COMMAND%%\"\n"
    echo "protonhax ls"
    printf "\tLists all currently running games\n"
    echo "protonhax run <appid> <cmd>"
    printf "\tRuns <cmd> in the context of <appid> with proton\n"
    echo "protonhax cmd <appid>"
    printf "\tRuns cmd.exe in the context of <appid>\n"
    echo "protonhax exec <appid> <cmd>"
    printf "\tRuns <cmd> in the context of <appid>\n"
}

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

c=$1
shift

if [[ "$c" == "init" ]]; then
    mkdir -p $phd/$SteamAppId
    printf "%s" "$1" > $phd/$SteamAppId/exe
    printf "%s" "$STEAM_COMPAT_DATA_PATH/pfx" > $phd/$SteamAppId/pfx
    env -0 > $phd/$SteamAppId/env
    "$@"
    ec=$?
    rm -r $phd/$SteamAppId
    exit $ec
elif [[ "$c" == "ls" ]]; then
    if [[ -d $phd ]]; then
        ls -1 $phd
    fi
elif [[ "$c" == "run" ]] || [[ "$c" == "cmd" ]] || [[ "$c" == "exec" ]]; then
    if [[ $# -lt 1 ]]; then
        usage
        exit 1
    fi
    if [[ ! -d $phd ]]; then
        printf "No app running with appid \"%s\"\n" "$1"
        exit 2
    fi
    if [[ ! -d $phd/$1 ]]; then
        printf "No app running with appid \"%s\"\n" "$1"
        exit 2
    fi
    SteamAppId=$1
    shift

    if [[ "$c" == "run" ]]; then
        if [[ $# -lt 1 ]]; then
            usage
            exit 1
        fi
        $(dirname $0)/envload $phd/$SteamAppId/env "$(cat $phd/$SteamAppId/exe)" run "$@"
    elif [[ "$c" == "cmd" ]]; then
        $(dirname $0)/envload $phd/$SteamAppId/env "$(cat $phd/$SteamAppId/exe)" run "$(cat $phd/$SteamAppId/pfx)/drive_c/windows/system32/cmd.exe"
    elif [[ "$c" == "exec" ]]; then
        if [[ $# -lt 1 ]]; then
            usage
            exit 1
        fi
        $(dirname $0)/envload $phd/$SteamAppId/env "$@"
    fi
else
    printf "Unknown command %s\n" "$c"
    usage
    exit 1
fi
